import fs from "node:fs/promises";
import path from "node:path";
import { buildNetwork, readMembers, ROOT, validateMember } from "./lib.js";

const out = path.join(ROOT, "dist");
const publicDir = path.join(ROOT, "public");
const members = await readMembers();
const handles = members.map((member) => member.handle);
const errors = members.flatMap((member) => validateMember(member, handles).map((error) => `${member.__file}: ${error}`));
if (errors.length) throw new Error(errors.join("\n"));

await fs.rm(out, { recursive: true, force: true });
await fs.cp(publicDir, out, { recursive: true });
await fs.mkdir(path.join(out, "data"), { recursive: true });
await fs.mkdir(path.join(out, "builders"), { recursive: true });

const network = buildNetwork(members.map(({ __file, ...member }) => member));
await fs.writeFile(path.join(out, "data", "network.json"), JSON.stringify(network, null, 2));

// ── Copy weekly rank snapshots ────────────────────────────────
// Reads snapshots/ at the project root (generated by scripts/snapshot.js).
// Copies the 10 most recent to dist/data/snapshots/ and writes an index.json
// listing them newest-first. The leaderboard page fetches this index to load
// real rank deltas. An empty index means no deltas are shown — correct behaviour
// before the weekly CI workflow has produced enough data.
const snapshotSrc = path.join(ROOT, "snapshots");
const snapshotDist = path.join(out, "data", "snapshots");
await fs.mkdir(snapshotDist, { recursive: true });

let snapshotIndex = { snapshots: [] };
try {
  const snapshotFiles = (await fs.readdir(snapshotSrc))
    .filter((f) => /^\d{4}-W\d{2}\.json$/.test(f))
    .sort()
    .reverse(); // lexicographic descending = newest ISO week first
  const toCopy = snapshotFiles.slice(0, 10);
  for (const file of toCopy) {
    await fs.copyFile(path.join(snapshotSrc, file), path.join(snapshotDist, file));
  }
  snapshotIndex = { snapshots: toCopy };
} catch {
  // snapshots/ directory missing or unreadable — index stays empty
}
await fs.writeFile(path.join(snapshotDist, "index.json"), JSON.stringify(snapshotIndex, null, 2));

const profileShell = await fs.readFile(path.join(publicDir, "profile.html"), "utf8");
for (const member of network.nodes) {
  const dir = path.join(out, "builders", member.handle);
  await fs.mkdir(dir, { recursive: true });
  await fs.writeFile(path.join(dir, "index.html"), profileShell
    .replaceAll("{{HANDLE}}", member.handle)
    .replaceAll("{{NAME}}", member.name)
    .replaceAll("{{BIO}}", member.bio));
}
await fs.rm(path.join(out, "profile.html"));
console.log(`Built ${network.nodes.length} profiles and network data in dist/.`);
